export const mainTheme = {
  components: {
    Menu: {
      iconSize: 24,
      itemActiveBg: "#5A199B",
      itemActiveColor: "white",
      itemHoverColor: "white",
      itemHoverBg: "#BB628E",
      itemColor: "black",
      itemSelectedBg: "#BB628E",
      itemSelectedColor: "white",
    },
    Form: {
      colorError: "#F5382C",
    },
    Input: {
      colorIcon: "#18191B",
    },
    Checkbox: {
      colorPrimary: "#2D665F",
      colorPrimaryHover: "#2D665F",
    },
    Select: {
      colorBgContainer: "rgba(0,0,0)",
      fontSize: 20,
      optionSelectedBg: "rgb(114,46,209)",
      optionSelectedColor: "rgb(255,255,255)",
      optionActiveBg: "rgb(216,165,255)",
      optionActiveColor: "#fff",
      colorBorder: "#FCC1BE",
      colorBgElevated: "rgb(226,205,255)",
      selectorBg: "#FAFAFA",
      colorTextPlaceholder: "rgb(0, 0, 0)",
      colorText: "#000",
      // activeOutlineColor: "#FCC1BE",
      // activeBorderColor: "#FCC1BE",
      hoverBorderColor: "#FCC1BE",
    },
    DatePicker: {
      fontSize: 20,
      colorBorder: "rgb(0, 0, 0,0.5)",
      colorTextPlaceholder: "rgb(0, 0, 0,0.5)",
    },
    Upload: {
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#18191B",
      colorBorderHover: "#18191B",
      colorText: "#18191B",
    },
    Table: {
      headerBg: "rgb(212,169,255)",
      colorBgContainer: "#FFFFFF",
      colorText: "#232323",
      borderColor: "#DFE1E3",
      headerColor: "#FFFFFF",
      fontSize: 18,
      footerColor: "#FE5C8E",
      colorPrimary: "#FFF9FD",
      // marginXXS: 4,
      colorLinkActive: "#FCC1BE",
      headerSplitColor: "rgb(255, 2555, 255)",
    },
    Pagination: {
      colorText: "rgba(255,255,255,0.88)",
      borderRadius: 20,
      itemActiveBg: "rgb(252,185,23)",
      colorPrimary: "rgb(255,255,255)",
      itemBg: "rgb(193,193,193)",
      colorBgTextHover: "rgb(245,236,155)",
      colorPrimaryHover: "rgb(0,0,0)",
      itemSize: 40,
    },
  },
};
